/** Design tokens for JS consumers (xterm, CodeMirror). Mirrors app.css @theme. */

export const color = {
  /** Anchors locked: purple #3D348B · gold #E6AF2E */
  purple: '#3d348b',
  gold: '#e6af2e',
  /** Void canvas — cool ink */
  dark: '#06050a',
  card: '#14131c',
  panel: '#0c0b12',
  grey: '#1c1b26',
  text: '#eceaf4',
  textDim: '#9a97a8',
  border: 'rgba(198, 192, 255, 0.07)',
  danger: '#ffb4ab',
  dangerBg: 'rgba(147, 0, 10, 0.35)',
  /** Plan / ask_user / lavender accents */
  lavender: '#aba3ff',
  lavenderBright: '#c6c0ff',
  lavenderSoft: '#c9c4ff',
  lavenderMuted: '#bcb6ff',
  lavenderDeep: '#897fff',
  violet: '#9e83ff',
  /** Success — cool mint, never competes with gold */
  success: '#3dba8b',
  successBright: '#7dcea0',
  successSoft: '#69ce9b',
  successText: '#79d9a7',
  successShell: '#8bd49c',
  successOut: '#c8e6c9',
  /** Errors (UI soft reds) */
  error: '#ff8a9b',
  errorSoft: '#ff9b9b',
  errorBright: '#ff6b81',
  /** Surfaces — purple-ink lift */
  shell: '#09080f',
  shellDeep: '#05040a',
  shellGreen: '#0a0f0c',
  diffBg: '#0c0f16',
  elevated: '#1a1924',
  popover: '#1f1e2a',
  sidebar: '#090811',
  /** Misc */
  amber: '#e8c66e',
  link: '#a8b8ff',
  selection: '#3d348b99',
  purpleBright: '#665bd6',
  purpleActive: '#6e65d9',
  comment: '#7a778c',
  keyword: '#c792ea',
  operator: '#a8b8ff',
  string: '#a8d98f',
  fn: '#7dd3fc',
  type: '#e8c66e',
  browserBg: '#0c0b12',
  browserSurface: '#1a1924',
  browserBorder: '#3a3850',
  browserText: '#eceaf4',
} as const

/** Shared xterm.js theme (TerminalStage + AgentStage vendor panes). */
export const xtermTheme = {
  background: color.shell,
  foreground: color.text,
  cursor: color.gold,
  cursorAccent: color.shell,
  selectionBackground: color.selection,
  black: color.grey,
  red: color.errorBright,
  green: color.successShell,
  yellow: color.gold,
  blue: color.operator,
  magenta: color.keyword,
  cyan: color.link,
  white: color.text,
  brightBlack: color.comment,
  brightRed: color.error,
  brightGreen: color.successOut,
  brightYellow: color.amber,
  brightBlue: color.fn,
  brightMagenta: color.lavenderSoft,
  brightCyan: color.link,
  brightWhite: color.text,
} as const
